# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86c6ab8f42cb90cd96205d5d0b409239df3ac6dfdaefb6f1cebd9bbf61dd582123d00523fca1c278580b2d601750f1770d82b543261087cee15b7ccea46a41be

test:
  secret_key_base: e8464c9bbaefb622e9bb8b4631dc8a365c7d45d7a69ae4f8b5602368ab0d509619665849d4f74e71df1bbb7e0657fbf9afa54e70b454f9721cdfa0ae9a9912b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
